# 这个文件是可选的，很多配置可以直接在Cloudflare Pages UI中设置

[build]
# 如果您的前端需要构建步骤 (例如使用Vite, React, Angular等框架编译)
# command = "npm install && npm run build"
command = "" # 您的前端是纯静态文件，不需要构建命令

[deployment.environments.production]
# publish 目录，指向您的前端文件根目录
publish = "frontend"

# 环境变量 (也可以在Cloudflare Pages UI中设置)
# [deployment.environments.production.vars]
# VITE_API_BASE_URL = "https://api.nihilistic.dpdns.org" # 确保指向您的Worker API地址 